OSX Installer: better error handling from brew failures
* When bre install fails, the installer will give pop up messages.
* It will also open the web page to the wiki entry
* Although all 3 scripts have the same error handling, only the first one will
  be executed.
* Added missing opencl script entry

diff --git a/CMakeModules/osx_install/opencl_scripts/postinstall b/CMakeModules/osx_install/opencl_scripts/postinstall
--- a/CMakeModules/osx_install/opencl_scripts/postinstall
+++ b/CMakeModules/osx_install/opencl_scripts/postinstall
@@ -6,8 +6,10 @@ set -o pipefail
 err_file=/tmp/AFInstallerOpenCL.err
 brew=/usr/local/bin/brew
 
+echo $(date) > $err_file
+
 if [ ! -f $brew ]; then
-    osascript -e 'tell app "Finder" to display dialog "Brew not installed. Please install brew at brew.sh"'
+    osascript -e 'tell app "Installer" to display dialog "Brew not installed. Please install brew at brew.sh"'
     echo "Brew not found" >> $err_file
     exit 1
 fi
@@ -19,5 +21,14 @@ if [ -z $user ]; then
     exit 1
 fi
 
-su $user -c "$brew tap homebrew/versions" 2> $err_file
-su $user -c "$brew install glfw3 fontconfig" 2> $err_file
+function deps_err
+{
+    osascript -e 'tell app "Installer" to display dialog "ArrayFire files installed but failed to install ArrayFire dependencies using Brew."'
+    osascript -e 'tell app "Installer" to display dialog "Visit https://github.com/arrayfire/arrayfire/wiki/Fixing-Common-OS-X-Installer-Failures to fix errors manually."'
+    open https://github.com/arrayfire/arrayfire/wiki/Fixing-Common-OS-X-Installer-Failures
+    echo "Dependencies failed to install" >> $err_file
+    exit 1
+}
+
+su $user -c "$brew tap homebrew/versions" >> $err_file 2>&1
+su $user -c "$brew install fftw glfw3 fontconfig" >> $err_file 2>&1 || deps_err
